config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :rockets, only: [:index, :show, :new, :create ] do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, only: [:show, :index, :update] do
    resources :reviews, only: [:new, :create]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :rocket
  belongs_to :user
  has_one :review
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
end

app/models/rocket.rb
class Rocket < ApplicationRecord
  belongs_to :user
  has_many :bookings

  has_one_attached :photo

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  def last_booking
    bookings.order(created_at: :desc).first
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :rockets
  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit

    # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  skip_after_action :verify_policy_scoped, only: :index
  def index
    @bookings = current_user.bookings
  end

  def show
    @booking = Booking.find(params[:id])
    authorize @booking
  end

  def new
    @booking = Booking.new
    @rocket = Rocket.find(params[:rocket_id])
    authorize @booking
  end

  def create
    @booking = Booking.new(status: "pending")
    @booking.rocket = Rocket.find(params[:rocket_id])
    authorize @booking
    @booking.user = current_user
    if @booking.save
      redirect_to rocket_path(@booking.rocket), notice: 'Booking was successfully created.'
    else
      render :new
    end
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.status = "confirmed"
    @booking.save
    redirect_to rocket_path(@booking.rocket)
    authorize @booking
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
    @booking = Booking.find(params[:booking_id])
    authorize @review
  end

  def create
    @review = Review.new(review_params)
    @review.booking = Booking.find(params[:booking_id])
    authorize @review
    if @review.save
      redirect_to booking_path(@review.booking), notice: 'Review was successfully created.'
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :comment)
  end
end

app/controllers/rockets_controller.rb
class RocketsController < ApplicationController
  before_action :set_rockets, only: [:index]

  def index
    @rocket = policy_scope(Rocket).order(created_at: :desc)

    @markers = @rocket.geocoded.map do |rocket|
      {
        lat: rocket.latitude,
        lng: rocket.longitude,
        info_window: render_to_string(partial: "info_window", locals: { rocket: rocket }),
        image_url: helpers.asset_url('saucer.gif')
      }
    end
  end

  def show
    @rocket = Rocket.find(params[:id])
    @booking = @rocket.last_booking
    authorize @rocket
  end

  def new
    @rocket = Rocket.new
    authorize @rocket
  end

  def create
    @rocket = Rocket.new(rocket_params)
    @rocket.user = current_user
    authorize @rocket
    if @rocket.save
      redirect_to rocket_path(@rocket)
    else
      render :new
    end
  end

  private

  def set_rockets
    @rockets = Rocket.all
  end

  def rocket_params
    params.require(:rocket).permit(:name, :price, :fuel, :description, :address, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="container">
  <h1>All your bookings</h1>
  <%= link_to "Back to all rockets", rockets_path, class: "btn btn-primary my-2" %>
  <div class="cards">
    <% @bookings.each do |booking| %>
      <% if policy(booking).create? %>
        <%= link_to booking_path(booking) do %>
          <div class="card">
            <p> Status: <%= booking.status %> </p>
            <p> Rocket: <%= booking.rocket.name%> </p>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="container">
  <p>Are you sure you want to book this awesome rocket?</p>
  <%= link_to "Back to all rockets", rockets_path, class: "btn btn-primary my-2" %>

  <%= simple_form_for [@rocket, @booking] do |f| %>
    <%= f.submit "Confirm booking", class: "btn btn-primary my-2"%>
  <% end %>
</div>

app/views/bookings/show.html.erb
<div class="container">
  <h1>Your Booking</h1>
  <%= link_to "Back to all rockets", rockets_path, class: "btn btn-primary my-2" %>
  <%= link_to "Create review", new_booking_review_path(@booking), class: "btn btn-primary my-2" %>
  <div class="cards">
    <div class="card">
      <p>Status: <%= @booking.status %></p>
      <% if @booking.review %>
        <p>Rating: <%= @booking.review.rating %></p>
        <p>Comment: <%=  @booking.review.comment %></p>
      <% else %>
        <p> Not rated yet.</p>
        <p> No comment yet.</p>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentARocket</title>
    <meta charset="UTF-8">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= stylesheet_pack_tag 'application' %>
  </head>

  <body>
    <%= render "/shared/navbar" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <%= render "/shared/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<head>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@500&display=swap" rel="stylesheet">
</head>

<body>
  <div class="banner">
    <h1><strong>R</strong>ent a <strong>R</strong>ocket</h1>
  </div>
  <div class="container">
    <%= link_to "Check out our rockets", rockets_path, class: "btn btn-primary my-2" %>
  </div>
</body>

app/views/reviews/create.html.erb
<h1>Hi</h1>
<%= simple_form for [@booking, @review] do |f|%>
<%= f.string :comment %>
<%= f.integer :rating %>
<%= f.submit "create", class: "btn btn-primary"%>
<%= end %>

app/views/reviews/new.html.erb
<div class="container">
  <h1>Leave a review</h1>
  <%= link_to "Back to all rockets", rockets_path, class: "btn btn-primary my-2" %>
  <%= link_to "Show my bookings", bookings_path, class: "btn btn-primary my-2" %>

  <%= simple_form_for [@booking, @review] do |f|%>
  <%= f.input :comment %>
  <%= f.input :rating %>
  <%= f.submit "create", class: "btn btn-primary my-2"%>
  <% end %>
</div>

app/views/rockets/_info_window.html.erb
<h2><%= rocket.name %></h2>
<p><%= rocket.address %></p>

app/views/rockets/index.html.erb
<div class="container">
  <h1>Marvel at our glorious rockets</h1>
  <br>
  <%= link_to "Create rocket", new_rocket_path, class: "btn btn-primary"%>
  <br>
    <div class="cards">
      <% @rockets.each do |rocket| %>
        <%= link_to rocket_path(rocket) do %>
          <div class="card">
            <% if rocket.photo.attached? %>
              <%= cl_image_tag rocket.photo.key , width: 340, heigth: 200, crop: :fill %>
            <% else %>
              <%= cl_image_tag("https://res.cloudinary.com/disabu2ji/image/upload/v1629381653/Rent%20a%20Rocket/soyuz_rocket_launch_rocket_dxw0wg.jpg", width: 340, height: 200, crop: :fill) %>
            <% end %>
            <br>
            <h3> <%= rocket.name %> </h3>
            <div class="card-header">
              <p> <%= rocket.price %>€</p>
              <p> &#x26FD; <%= rocket.fuel %></p>
            </div>
            <div class="description">
              <p><%= rocket.description %></p>
            </div>
              <br>
            <div class="address">
              <p> &#x1F30D; <%= rocket.address %>
            </div>
          </div>
        <% end %>
      <% end %>
     <div id="map"
     style="width: 100%; height: 600px;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
  </div>
</div>

app/views/rockets/new.html.erb
<div class="container">
  <h1>Create a new rocket</h1>
  <%= link_to "Back to all rockets", rockets_path, class: "btn btn-primary my-2"%>

  <%= simple_form_for @rocket do |f| %>
  <%= f.input :name %>
  <%= f.input :price %>
  <%= f.input :fuel %>
  <%= f.input :description %>
  <%= f.input :address %>
  <%= f.input :photo, as: :file %>
  <%= f.submit "Create Rocket", class: "btn btn-primary my-2" %>
  <% end %>
</div>

app/views/rockets/show.html.erb
<div class="container">
  <h1><%=  @rocket.name %></h1>

  <%= link_to "Book rocket", new_rocket_booking_path(@rocket), class: "btn btn-primary my-2" %>
  <%= link_to "Show my bookings", bookings_path, class: "btn btn-primary my-2" %>
  <%= link_to "Back to all rockets", rockets_path, class: "btn btn-primary my-2" %>

  <div class="cards">
    <div class="card">
      <% if @rocket.photo.attached? %>
        <%= cl_image_tag @rocket.photo.key , width: 340, height: 200, crop: :fill %>
      <% else %>
        <%= cl_image_tag("https://res.cloudinary.com/disabu2ji/image/upload/v1629381653/Rent%20a%20Rocket/soyuz_rocket_launch_rocket_dxw0wg.jpg", width: 340, height: 200, crop: :fill) %>
      <% end %>
      <h3> <%= @rocket.name %> </h3>
      <div class="card-header">
        <p> <%= @rocket.price %>€</p>
        <p> &#x26FD; <%= @rocket.fuel %></p>
      </div>
      <div class="description">
        <p><%= @rocket.description %></p>
      </div>
      <div class="address">
        <p> &#x1F30D; <%= @rocket.address %>
      </div>
      <div class="booked">
        <% unless @rocket.bookings.empty? %>
          <% if policy(@rocket).update? %>
            <%= link_to "Confirm booking", booking_path(@booking), method: "patch", class: "btn btn-primary"%>
          <% end %>
          <%= @booking.status %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="cont">
  <h4>Contact Information</h4>
  <div class="footer">
    <div class="person">
      <h6>Janus Vollmer</h6>
      <div class="footer-links">
        <a href="https://github.com/noesch"><i class="fab fa-github"></i></a>
        <a href="https://www.linkedin.com/in/janus-vollmer-9a486a94"><i class="fab fa-linkedin"></i></a>
      </div>
    </div>
    <div class="person">
      <h6>Louis Neubauer</h6>
      <div class="footer-links">
        <a href="https://github.com/louisneubauer"><i class="fab fa-github"></i></a>
        <a href="https://www.linkedin.com/in/louis-neubauer-1193681bb"><i class="fab fa-linkedin"></i></a>
      </div>
    </div>
    <div class="person">
      <h6>Max von Wedemeyer</h6>
      <div class="footer-links">
        <a href="https://github.com/maxeduard"><i class="fab fa-github"></i></a>
        <a href="https://www.linkedin.com/in/max-eduard-v-wedemeyer-aba97a157"><i class="fab fa-linkedin"></i></a>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to rockets_path, class: "navbar-brand" do %>
    <%= image_tag "rakete-symbol.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home", root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Bookings", bookings_path, class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <%= image_tag "https://t4.ftcdn.net/jpg/00/64/67/63/360_F_64676383_LdbmhiNM6Ypzb3FM4PPuFP9rHe7ri8Ju.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <% if current_user %>
            <%= link_to "Log out", destroy_user_session_path, method: "delete", class: "dropdown-item"%>
            <% else %>
            <%= link_to "Log in", new_user_session_path, class: "dropdown-item" %>
            <%= link_to "Sign up", new_user_registration_path, class: "dropdown-item" %>
          <% end %>
        </div>
      </li>
    </ul>
  </div>
</div>